# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-02 18:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('a_lower', models.IntegerField()),
                ('a_upper', models.IntegerField()),
                ('b_lower', models.IntegerField()),
                ('b_upper', models.IntegerField()),
            ],
        ),
    ]
