# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-08 15:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character', models.CharField(max_length=1)),
                ('count', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='case',
            name='a_lower',
            field=models.IntegerField(verbose_name=' a'),
        ),
        migrations.AlterField(
            model_name='case',
            name='a_upper',
            field=models.IntegerField(verbose_name=' A'),
        ),
        migrations.AlterField(
            model_name='case',
            name='b_lower',
            field=models.IntegerField(verbose_name=' b'),
        ),
        migrations.AlterField(
            model_name='case',
            name='b_upper',
            field=models.IntegerField(verbose_name=' B'),
        ),
        migrations.AddField(
            model_name='block',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cases.Case'),
        ),
    ]
