# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-11 16:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0002_auto_20161108_1554'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='a_lower',
        ),
        migrations.RemoveField(
            model_name='case',
            name='a_upper',
        ),
        migrations.RemoveField(
            model_name='case',
            name='b_lower',
        ),
        migrations.RemoveField(
            model_name='case',
            name='b_upper',
        ),
    ]
